const x = '10'

try{
    x = 9
}catch(err){
    console.log(err)
}